### ISSUE TITLE
create_reconnecting_redis is deprecated

### ISSUE THREAD

**Issue by dfee** [asphalt-framework/asphalt-redis#1]
https://github.com/aio-libs/aioredis/blob/f504886930b938576779795916ce7c88b302d195/aioredis/__init__.py#L59

it seems this should be migrated to `create_pool`.

**Comment by agronholm** [comment]
There is no mention of this in the v0.3.0 documentation?

**Comment by agronholm** [comment]
Also, won't create_pool() return an object of different type from the resource type asphalt-redis creates now? If so, a major version bump is required.

**Comment by agronholm** [comment]
This is a bit old but v2.1.0 fixed this last month.
